svchost: :8080
dbuser: root
dbpassword: "qwe123Q!"
dbhost: localhost
dbname: image_uploader
service:
  address: "http://levsha.dev"
  upload_dir: "/var/www/levsha/web/uploads"
  upload_url: "/uploads"
  thumb_dir: "/thumbs"
  thumb_suffix: "_thumb"
