svchost: :8080
dbuser: root
dbpassword: "qwe123Q!"
dbhost: localhost
dbname: image_uploader
mode: debug
service:
  address: "http://localhost"
  upload_dir: "/tmp/uploads"
  upload_url: "/uploads"
  thumb_dir: "/thumbs"
  thumb_suffix: "_thumb"
